export const levels = [
  {
    complexity: 0,
    width: 2,
    height: 2,
    nrOfColors: 2,
    nrOfFixedColors: 1,
    points: 5,
    challengeBlocks: [],
    name: "",
  },
  {
    complexity: 0,
    width: 2,
    height: 2,
    nrOfColors: 2,
    nrOfFixedColors: 1,
    points: 5,
    challengeBlocks: [],
    name: "",
  },
  {
    complexity: 1,
    width: 3,
    height: 1,
    nrOfColors: 3,
    nrOfFixedColors: 1,
    points: 7,
    challengeBlocks: [],
    name: "",
  },
];
