export const PIECES = {
  allPossiblePieces: [
    {
      name: "topleftcorner1",
      topTab: 0,
      rightTab: -1,
      bottomTab: -1,
      leftTab: 0,
    },
    {
      name: "topleftcorner2",
      topTab: 0,
      rightTab: 1,
      bottomTab: 1,
      leftTab: 0,
    },
    {
      name: "topleftcorner3",
      topTab: 0,
      rightTab: 1,
      bottomTab: -1,
      leftTab: 0,
    },
    {
      name: "topleftcorner4",
      topTab: 0,
      rightTab: -1,
      bottomTab: 1,
      leftTab: 0,
    },
    {
      name: "toprightcorner1",
      topTab: 0,
      rightTab: 0,
      bottomTab: -1,
      leftTab: -1,
    },
    {
      name: "toprightcorner2",
      topTab: 0,
      rightTab: 0,
      bottomTab: 1,
      leftTab: 1,
    },
    {
      name: "toprightcorner3",
      topTab: 0,
      rightTab: 0,
      bottomTab: -1,
      leftTab: 1,
    },
    {
      name: "toprightcorner4",
      topTab: 0,
      rightTab: 0,
      bottomTab: 1,
      leftTab: -1,
    },
    {
      name: "bottomleftcorner1",
      topTab: -1,
      rightTab: -1,
      bottomTab: 0,
      leftTab: 0,
    },
    {
      name: "bottomleftcorner2",
      topTab: 1,
      rightTab: 1,
      bottomTab: 0,
      leftTab: 0,
    },
    {
      name: "bottomleftcorner3",
      topTab: 1,
      rightTab: -1,
      bottomTab: 0,
      leftTab: 0,
    },
    {
      name: "bottomleftcorner4",
      topTab: -1,
      rightTab: 1,
      bottomTab: 0,
      leftTab: 0,
    },
    {
      name: "bottomrightcorner1",
      topTab: -1,
      rightTab: 0,
      bottomTab: 0,
      leftTab: -1,
    },
    {
      name: "bottomrightcorner2",
      topTab: 1,
      rightTab: 0,
      bottomTab: 0,
      leftTab: 1,
    },
    {
      name: "bottomrightcorner3",
      topTab: 1,
      rightTab: 0,
      bottomTab: 0,
      leftTab: -1,
    },
    {
      name: "bottomrightcorner4",
      topTab: -1,
      rightTab: 0,
      bottomTab: 0,
      leftTab: 1,
    },
    {
      name: "middle1",
      topTab: -1,
      rightTab: -1,
      bottomTab: -1,
      leftTab: -1,
    },
    {
      name: "middle2",
      topTab: 1,
      rightTab: 1,
      bottomTab: 1,
      leftTab: 1,
    },
    {
      name: "middle3",
      topTab: 1,
      rightTab: -1,
      bottomTab: -1,
      leftTab: -1,
    },
    {
      name: "middle4",
      topTab: -1,
      rightTab: 1,
      bottomTab: -1,
      leftTab: -1,
    },
    {
      name: "middle5",
      topTab: -1,
      rightTab: -1,
      bottomTab: 1,
      leftTab: -1,
    },
    {
      name: "middle6",
      topTab: -1,
      rightTab: -1,
      bottomTab: -1,
      leftTab: 1,
    },
    {
      name: "middle7",
      topTab: 1,
      rightTab: 1,
      bottomTab: -1,
      leftTab: -1,
    },
    {
      name: "middle8",
      topTab: -1,
      rightTab: 1,
      bottomTab: 1,
      leftTab: -1,
    },
    {
      name: "middle9",
      topTab: -1,
      rightTab: -1,
      bottomTab: 1,
      leftTab: 1,
    },
    {
      name: "middle10",
      topTab: 1,
      rightTab: -1,
      bottomTab: -1,
      leftTab: 1,
    },
    {
      name: "middle11",
      topTab: 1,
      rightTab: 1,
      bottomTab: 1,
      leftTab: -1,
    },
    {
      name: "middle12",
      topTab: -1,
      rightTab: 1,
      bottomTab: 1,
      leftTab: 1,
    },
    {
      name: "middle13",
      topTab: 1,
      rightTab: -1,
      bottomTab: 1,
      leftTab: 1,
    },
    {
      name: "middle14",
      topTab: 1,
      rightTab: 1,
      bottomTab: -1,
      leftTab: 1,
    },
    {
      name: "middle15",
      topTab: 1,
      rightTab: -1,
      bottomTab: 1,
      leftTab: -1,
    },
    {
      name: "middle16",
      topTab: -1,
      rightTab: 1,
      bottomTab: -1,
      leftTab: 1,
    },
    {
      name: "top1",
      topTab: 0,
      rightTab: -1,
      bottomTab: -1,
      leftTab: -1,
    },
    {
      name: "top2",
      topTab: 0,
      rightTab: 1,
      bottomTab: 1,
      leftTab: 1,
    },
    {
      name: "top3",
      topTab: 0,
      rightTab: 1,
      bottomTab: -1,
      leftTab: -1,
    },
    {
      name: "top4",
      topTab: 0,
      rightTab: -1,
      bottomTab: 1,
      leftTab: -1,
    },
    {
      name: "top5",
      topTab: 0,
      rightTab: -1,
      bottomTab: -1,
      leftTab: 1,
    },
    {
      name: "top6",
      topTab: 0,
      rightTab: 1,
      bottomTab: 1,
      leftTab: -1,
    },
    {
      name: "top7",
      topTab: 0,
      rightTab: -1,
      bottomTab: 1,
      leftTab: 1,
    },
    {
      name: "top8",
      topTab: 0,
      rightTab: 1,
      bottomTab: -1,
      leftTab: 1,
    },
    {
      name: "bottom1",
      topTab: -1,
      rightTab: -1,
      bottomTab: 0,
      leftTab: -1,
    },
    {
      name: "bottom2",
      topTab: 1,
      rightTab: 1,
      bottomTab: 0,
      leftTab: 1,
    },
    {
      name: "bottom3",
      topTab: -1,
      rightTab: 1,
      bottomTab: 0,
      leftTab: -1,
    },
    {
      name: "bottom4",
      topTab: 1,
      rightTab: -1,
      bottomTab: 0,
      leftTab: -1,
    },
    {
      name: "bottom5",
      topTab: -1,
      rightTab: -1,
      bottomTab: 0,
      leftTab: 1,
    },
    {
      name: "bottom6",
      topTab: -1,
      rightTab: 1,
      bottomTab: 0,
      leftTab: 1,
    },
    {
      name: "bottom7",
      topTab: 1,
      rightTab: -1,
      bottomTab: 0,
      leftTab: 1,
    },
    {
      name: "bottom8",
      topTab: 1,
      rightTab: 1,
      bottomTab: 0,
      leftTab: -1,
    },
  ],
};
